apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: gcr.io/dota-440301/my-backend-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "mysql+pymysql://admin:proyecto-cloud@database-1-instance-1.crmwqkaq0x91.us-east-1.rds.amazonaws.com:3306/contacts_db"
